/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HairRouteImport } from './routes/hair'
import { Route as CraftingRouteImport } from './routes/crafting'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AlterationsRouteImport } from './routes/alterations'
import { Route as IndexRouteImport } from './routes/index'

const HairRoute = HairRouteImport.update({
  id: '/hair',
  path: '/hair',
  getParentRoute: () => rootRouteImport,
} as any)
const CraftingRoute = CraftingRouteImport.update({
  id: '/crafting',
  path: '/crafting',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AlterationsRoute = AlterationsRouteImport.update({
  id: '/alterations',
  path: '/alterations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alterations': typeof AlterationsRoute
  '/contact': typeof ContactRoute
  '/crafting': typeof CraftingRoute
  '/hair': typeof HairRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alterations': typeof AlterationsRoute
  '/contact': typeof ContactRoute
  '/crafting': typeof CraftingRoute
  '/hair': typeof HairRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alterations': typeof AlterationsRoute
  '/contact': typeof ContactRoute
  '/crafting': typeof CraftingRoute
  '/hair': typeof HairRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/alterations' | '/contact' | '/crafting' | '/hair'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/alterations' | '/contact' | '/crafting' | '/hair'
  id: '__root__' | '/' | '/alterations' | '/contact' | '/crafting' | '/hair'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlterationsRoute: typeof AlterationsRoute
  ContactRoute: typeof ContactRoute
  CraftingRoute: typeof CraftingRoute
  HairRoute: typeof HairRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/hair': {
      id: '/hair'
      path: '/hair'
      fullPath: '/hair'
      preLoaderRoute: typeof HairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crafting': {
      id: '/crafting'
      path: '/crafting'
      fullPath: '/crafting'
      preLoaderRoute: typeof CraftingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alterations': {
      id: '/alterations'
      path: '/alterations'
      fullPath: '/alterations'
      preLoaderRoute: typeof AlterationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlterationsRoute: AlterationsRoute,
  ContactRoute: ContactRoute,
  CraftingRoute: CraftingRoute,
  HairRoute: HairRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
